"""remocao de quantidade em livro

Revision ID: a276d09ba5da
Revises: d467f68aeec8
Create Date: 2025-12-11 21:53:18.813881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a276d09ba5da'
down_revision: Union[str, Sequence[str], None] = 'd467f68aeec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
